# Generated by Django 4.1.5 on 2024-10-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_alter_profile_cover_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
