version: '3'

services:
  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile_dev
    volumes:
      - ./app:/app 
    ports:
      - "8080:80"
    environment:
      - PASS_SERVICE_ADDR=password-service
      - PASS_SERVICE_PORT=8000
    networks:
      - front-tier
      - back-tier
  password-service:
    build:
      context: .
      dockerfile: password-service/Dockerfile_dev
    volumes:
      - ./password-service:/password-service
    ports:
      - "8000:8000"
    networks:
      - back-tier

networks:
  front-tier: {}
  back-tier:
    driver: bridge
    internal: true